### ISSUE TITLE
Typo in ID for Vardis Egen

### ISSUE THREAD

**Issue by cj2001** [mathbeveridge/gameofthrones#2]
There are a few edges in the `got-s1-edges.csv` file that have a typo in it.  In particular, they are:

```
VARDIS_EGAN,TYRION,9,SEASON1
LYSA,VARDIS_EGAN,7,SEASON1
```
In the node file, there is no corresponding ID of `VARDIS_EGAN` but rather `VARDIS_EGEN`.  Just a quick clean up of those two lines should solve the problem.

**Comment by mathbeveridge** [comment]
Fixed. Thanks!
